name: Test

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  JAVA_DISTRIBUTION: "temurin"
  JAVA_VERSION: "25"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Run Test 01
        run: |
          chmod +x tools/HardwareSimulator.sh
          for test in projects/01/*.tst; do
            echo "Running $test"
            sh tools/HardwareSimulator.sh $test
          done

      - name: Run Test 02
        run: |
          chmod +x tools/HardwareSimulator.sh
          for test in projects/02/*.tst; do
            echo "Running $test"
            sh tools/HardwareSimulator.sh $test
          done

      - name: Run Test 03
        run: |
          chmod +x tools/HardwareSimulator.sh
          for test in projects/03/a/*.tst; do
            echo "Running $test"
            sh tools/HardwareSimulator.sh $test
          done
          for test in projects/03/b/*.tst; do
            echo "Running $test"
            sh tools/HardwareSimulator.sh $test
          done
